# Generated by Django 5.0.6 on 2024-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realme', '0004_mobile_battery_mobile_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='color',
            field=models.CharField(default=50, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='storage',
            field=models.CharField(default=50, max_length=255),
            preserve_default=False,
        ),
    ]
