# Generated by Django 5.0.6 on 2024-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realme', '0005_mobile_color_mobile_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='color',
            new_name='camera',
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
