# Generated by Django 5.0.6 on 2024-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realme', '0007_mobile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(default=50, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth',
            field=models.CharField(default=50, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mic',
            field=models.CharField(default=50, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.CharField(default=50, max_length=255),
            preserve_default=False,
        ),
    ]
